name: Test
on:
  pull_request:
jobs:
  run:
    name: Respond to reports of a new problem
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack (if all checks passed)
        uses: slackapi/slack-github-action@v2.1.1
        with:
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          method: chat.postMessage
          errors: "true"
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "Pull Request is ready to merge"
            blocks:
              - type: section
                text:
                  type: mrkdwn
                  text: |
                    :rocket: *Pull Request Ready to Merge*
                    
                    *https://github.com/${{ github.repository }}*
