name: Update dependencies

on:
  repository_dispatch:

jobs:
  context:
    name: Output stringified context
    runs-on: ubuntu-latest
    steps:
    - name: Print the GitHub context
      run: echo "${{ toJson(github) }}"

  dependabot:
    name: Merge known versions
    runs-on: ubuntu-latest
      # if: github.event.client_payload.sender.login === 'dependabot[bot]'
    steps:
      # - name: Generate a GitHub token
      - name: Print the GitHub context
        run: echo "${{ toJson(github) }}"

      - name: Collect update metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Note the updated dependencies
        run: echo "${{ steps.metadata.outputs.dependency-names }}"

      - name: Merge @slackapi packages
        if: |
          (
            steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
            steps.metadata.outputs.update-type == 'version-update:semver-minor'
          ) && (
            steps.metadata.outputs.dependency-names == '@slack/bolt'
          )
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --squash "$PR_URL"
        env:
          GH_TOKEN: ${{ steps.ghtoken.outputs.token }}
          PR_URL: ${{ github.event.client_payload.pull_request.html_url }}

