# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Spam the API
on:
  push:
jobs:
  run:
    name: Make requests with a webhook trigger
    runs-on: ubuntu-latest
    steps:
      - uses: slackapi/slack-github-action@v2.0.0
        with:
          errors: true
          method: canvases.create
          retries: 5
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            title: "LGTM!"
      - uses: slackapi/slack-github-action@v2.0.0
        with:
          errors: true
          method: canvases.create
          retries: 5
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            title: "LGTM!"
      - uses: slackapi/slack-github-action@v2.0.0
        with:
          errors: true
          method: canvases.create
          retries: 5
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            title: "LGTM!"
      - uses: slackapi/slack-github-action@v2.0.0
        with:
          errors: true
          method: canvases.create
          retries: 5
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            title: "LGTM!"
      - uses: slackapi/slack-github-action@v2.0.0
        with:
          errors: true
          method: canvases.create
          retries: 5
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            title: "LGTM!"
      - uses: slackapi/slack-github-action@v2.0.0
        with:
          errors: true
          method: canvases.create
          retries: 5
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            title: "LGTM!"
      - uses: slackapi/slack-github-action@v2.0.0
        with:
          errors: true
          method: canvases.create
          retries: 5
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            title: "LGTM!"
      - uses: slackapi/slack-github-action@v2.0.0
        with:
          errors: true
          method: canvases.create
          retries: 5
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            title: "LGTM!"
      - uses: slackapi/slack-github-action@v2.0.0
        with:
          errors: true
          method: canvases.create
          retries: 5
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            title: "LGTM!"
      - uses: slackapi/slack-github-action@v2.0.0
        with:
          errors: true
          method: canvases.create
          retries: 5
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            title: "LGTM!"
      - uses: slackapi/slack-github-action@v2.0.0
        with:
          errors: true
          method: canvases.create
          retries: 5
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            title: "LGTM!"
      - uses: slackapi/slack-github-action@v2.0.0
        with:
          errors: true
          method: canvases.create
          retries: 5
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            title: "LGTM!"
      - uses: slackapi/slack-github-action@v2.0.0
        with:
          errors: true
          method: canvases.create
          retries: 5
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            title: "LGTM!"
      - uses: slackapi/slack-github-action@v2.0.0
        with:
          errors: true
          method: canvases.create
          retries: 5
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            title: "LGTM!"
      - uses: slackapi/slack-github-action@v2.0.0
        with:
          errors: true
          method: canvases.create
          retries: 5
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            title: "LGTM!"
      - uses: slackapi/slack-github-action@v2.0.0
        with:
          errors: true
          method: canvases.create
          retries: 5
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            title: "LGTM!"
      - uses: slackapi/slack-github-action@v2.0.0
        with:
          errors: true
          method: canvases.create
          retries: 5
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            title: "LGTM!"
      - uses: slackapi/slack-github-action@v2.0.0
        with:
          errors: true
          method: canvases.create
          retries: 5
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            title: "LGTM!"
      - uses: slackapi/slack-github-action@v2.0.0
        with:
          errors: true
          method: canvases.create
          retries: 5
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            title: "LGTM!"
      - uses: slackapi/slack-github-action@v2.0.0
        with:
          errors: true
          method: canvases.create
          retries: 5
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            title: "LGTM!"
