# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Spam the API
on:
  push:
jobs:
  run:
    name: Make requests with a webhook trigger
    runs-on: ubuntu-latest
    steps:
      - uses: slackapi/slack-github-action@v2.0.0
        id: canvases0
        with:
          errors: true
          method: canvases.create
          retries: 5
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            title: "LGTM!"

      - name: Search email detail
        if: ${{ steps.canvases0.outputs.ok }}
        run: |
          CANVAS_ID=$(echo '${{ steps.canvases0.outputs.response }}' | jq -r '.canvas_id')
          echo "CANVAS_ID=$CANVAS_ID" >> $GITHUB_ENV

      - uses: slackapi/slack-github-action@v2.0.0
        with:
          errors: true
          method: canvases.delete
          retries: 5
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            canvas_id: "${{ env.CANVAS_ID }}"

      #
      ##
      #

      - uses: slackapi/slack-github-action@v2.0.0
        id: canvases1
        with:
          errors: true
          method: canvases.create
          retries: 5
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            title: "LGTM!"

      - name: Search email detail
        if: ${{ steps.canvases1.outputs.ok }}
        run: |
          CANVAS_ID=$(echo '${{ steps.canvases1.outputs.response }}' | jq -r '.canvas_id')
          echo "CANVAS_ID=$CANVAS_ID" >> $GITHUB_ENV

      - uses: slackapi/slack-github-action@v2.0.0
        with:
          errors: true
          method: canvases.delete
          retries: 5
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            canvas_id: "${{ env.CANVAS_ID }}"

      #
      ##
      #

      - uses: slackapi/slack-github-action@v2.0.0
        id: canvases2
        with:
          errors: true
          method: canvases.create
          retries: 5
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            title: "LGTM!"

      - name: Search email detail
        if: ${{ steps.canvases2.outputs.ok }}
        run: |
          CANVAS_ID=$(echo '${{ steps.canvases2.outputs.response }}' | jq -r '.canvas_id')
          echo "CANVAS_ID=$CANVAS_ID" >> $GITHUB_ENV

      - uses: slackapi/slack-github-action@v2.0.0
        with:
          errors: true
          method: canvases.delete
          retries: 5
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            canvas_id: "${{ env.CANVAS_ID }}"

      #
      ##
      #

      - uses: slackapi/slack-github-action@v2.0.0
        id: canvases3
        with:
          errors: true
          method: canvases.create
          retries: 5
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            title: "LGTM!"

      - name: Search email detail
        if: ${{ steps.canvases3.outputs.ok }}
        run: |
          CANVAS_ID=$(echo '${{ steps.canvases3.outputs.response }}' | jq -r '.canvas_id')
          echo "CANVAS_ID=$CANVAS_ID" >> $GITHUB_ENV

      - uses: slackapi/slack-github-action@v2.0.0
        with:
          errors: true
          method: canvases.delete
          retries: 5
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            canvas_id: "${{ env.CANVAS_ID }}"

      #
      ##
      #

      - uses: slackapi/slack-github-action@v2.0.0
        id: canvases4
        with:
          errors: true
          method: canvases.create
          retries: 5
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            title: "LGTM!"

      - name: Search email detail
        if: ${{ steps.canvases4.outputs.ok }}
        run: |
          CANVAS_ID=$(echo '${{ steps.canvases4.outputs.response }}' | jq -r '.canvas_id')
          echo "CANVAS_ID=$CANVAS_ID" >> $GITHUB_ENV

      - uses: slackapi/slack-github-action@v2.0.0
        with:
          errors: true
          method: canvases.delete
          retries: 5
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            canvas_id: "${{ env.CANVAS_ID }}"
