name: Tests
on:
  pull_request_target:
    types: [opened, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  access_check:
    runs-on: ubuntu-latest
    steps:
      - name: Output event
        run: echo "${{ github.event_name }}"

      - name: Checkout the Slack GitHub Action
        uses: actions/checkout@v4
        with:
          repository: slackapi/slack-github-action
          ref: v2-development
          path: ./slack-send
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: ./slack-send/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: ./slack-send

      - name: Post a token message into channel
        uses: ./slack-send
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "Action happens at <https://github.com/${{ github.repository }}>"

      - name: Check user permissions
        if: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.author_association != 'MEMBER' }}
        run: |
          echo "Action was not triggered by an organization member. Exiting now."
          exit 1
