name: Tests
on:
  pull_request_target:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  access_check:
    runs-on: ubuntu-latest
    steps:
    - name: Output event
      run: echo ${{ github.event_name }}
    - name: Output GitHub
      run: echo ${{ toJson(github) }}
    - name: Output GitHub context
      run: echo ${{ toJson(github.context) }}
    - name: Check user permissions
      if: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.author_association != 'MEMBER' }}
      run: |
        echo "Action was not triggered by an organization member. Exiting now."
        exit 1

  slack-notify:
    name: "Post release notes to Slack"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Send release notes to Slack"
        uses: "slackapi/slack-github-action@v1.25.0"
        with:
          channel-id: C04CRUE6MU3
          payload: |
            {
              "text": "Release notes",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "# Release notes - 12"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ github.event.release.body }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
