name: Tests
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  access_check:
    runs-on: ubuntu-latest
    steps:
      - name: Post a token message into channel
        uses: zimeg/slack-github-action@v2.0.0-rc.2
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "Action happens at <https://github.com/${{ github.repository }}>"
