name: Share errors from tests after a merge
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  run:
    name: Merged tests
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Mock a test failure
        run: exit 1
      - name: Send message into channel
        if: failure()
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: https://hooks.slack.com/triggers/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
          webhook-type: webhook-trigger
          payload: |
            "repository": "${{ github.repository }}",
            "pull_request_username": "${{ github.event.pull_request.user.login }}",
            "pull_request_title": ${{ toJSON(github.event.pull_request.title) }},
            "pull_request_branch": "${{ github.event.pull_request.head.ref }}",
            "pull_request_url": "${{ github.event.pull_request.html_url }}",
