name: Templatize variables

on: push

jobs:
  templatize:
    name: Replace placeholders
    runs-on: ubuntu-latest
    steps:
      - name: Print the variable
        run: echo ${{ vars.SLACK_NOTIFICATION }}

      - name: Replace the template
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: ${{ vars.SLACK_NOTIFICATION }}
        env:
          NUMBER: 12
