name: Templatize variables

on: push

jobs:
  templatize:
    name: Replace placeholders
    runs-on: ubuntu-latest
    steps:
      - name: Replace the template
        uses: slackapi/slack-github-action@v2.0.0
        with:
          errors: true
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload-templated: true
          payload: |
            text: "Greetings!"
        env:
          NUMBER: 12
